---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hostdev-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: hostdev-device-plugin-ds
  template:
    metadata:
      labels:
        name: hostdev-device-plugin-ds
    spec:
      securityContext:
        privileged: true
        seccompProfile:
          type: Unconfined
      hostNetwork: true
      imagePullPolicy: Always
      containers:
      - name: hostdev
        image: ghcr.io/thehonker/k8s-hostdev-plugin:latest
        args: ["--devs", "/dev/mem:rw,/dev/fuse:rwm,/dev/kfd:rw,/dev/dri:rw"]
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
